POST http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQHVzZXIuY29tIiwiZXhwIjoxNzEyMTU3Mjk5LCJ1c2VySWQiOjJ9.rkcklXw_ga-dzn8xkmz73t5vUPXS9Ra66djrddnc3Qs

